platform :ios, '7.0'

pod 'FSHelper'
pod 'AFNetworking'
pod 'MagicalRecord'
pod 'SVProgressHUD'
pod 'SDWebImage', '~> 3.7'
#pod 'NSDate-Extensions'
#pod 'Reachability'
#pod 'SSKeychain'
#pod 'NSData+Base64'
#pod 'MKStoreKit'
#pod 'NSDate-Extensions'